# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ChargingPoint(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, node: str=None):  # noqa: E501
        """ChargingPoint - a model defined in Swagger

        :param id: The id of this ChargingPoint.  # noqa: E501
        :type id: str
        :param node: The node of this ChargingPoint.  # noqa: E501
        :type node: str
        """
        self.swagger_types = {
            'id': str,
            'node': str
        }

        self.attribute_map = {
            'id': 'id',
            'node': 'node'
        }

        self._id = id
        self._node = node

    @classmethod
    def from_dict(cls, dikt) -> 'ChargingPoint':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ChargingPoint of this ChargingPoint.  # noqa: E501
        :rtype: ChargingPoint
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this ChargingPoint.


        :return: The id of this ChargingPoint.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this ChargingPoint.


        :param id: The id of this ChargingPoint.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def node(self) -> str:
        """Gets the node of this ChargingPoint.

        ID for the connected node  # noqa: E501

        :return: The node of this ChargingPoint.
        :rtype: str
        """
        return self._node

    @node.setter
    def node(self, node: str):
        """Sets the node of this ChargingPoint.

        ID for the connected node  # noqa: E501

        :param node: The node of this ChargingPoint.
        :type node: str
        """
        if node is None:
            raise ValueError("Invalid value for `node`, must not be `None`")  # noqa: E501

        self._node = node
