# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.electric_vehicle import ElectricVehicle  # noqa: F401,E501
from swagger_server import util


class ChargingStation(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, bus: str=None, phases: int=None, k_v: float=None, max_charging_power_k_w: float=None, charging_efficiency: float=None, powerfactor: float=None, type_application: str='residential', hosted_ev: List[ElectricVehicle]=None):  # noqa: E501
        """ChargingStation - a model defined in Swagger

        :param id: The id of this ChargingStation.  # noqa: E501
        :type id: str
        :param bus: The bus of this ChargingStation.  # noqa: E501
        :type bus: str
        :param phases: The phases of this ChargingStation.  # noqa: E501
        :type phases: int
        :param k_v: The k_v of this ChargingStation.  # noqa: E501
        :type k_v: float
        :param max_charging_power_k_w: The max_charging_power_k_w of this ChargingStation.  # noqa: E501
        :type max_charging_power_k_w: float
        :param charging_efficiency: The charging_efficiency of this ChargingStation.  # noqa: E501
        :type charging_efficiency: float
        :param powerfactor: The powerfactor of this ChargingStation.  # noqa: E501
        :type powerfactor: float
        :param type_application: The type_application of this ChargingStation.  # noqa: E501
        :type type_application: str
        :param hosted_ev: The hosted_ev of this ChargingStation.  # noqa: E501
        :type hosted_ev: List[ElectricVehicle]
        """
        self.swagger_types = {
            'id': str,
            'bus': str,
            'phases': int,
            'k_v': float,
            'max_charging_power_k_w': float,
            'charging_efficiency': float,
            'powerfactor': float,
            'type_application': str,
            'hosted_ev': List[ElectricVehicle]
        }

        self.attribute_map = {
            'id': 'id',
            'bus': 'bus',
            'phases': 'phases',
            'k_v': 'kV',
            'max_charging_power_k_w': 'max_charging_power_kW',
            'charging_efficiency': 'charging_efficiency',
            'powerfactor': 'powerfactor',
            'type_application': 'type_application',
            'hosted_ev': 'hosted_ev'
        }

        self._id = id
        self._bus = bus
        self._phases = phases
        self._k_v = k_v
        self._max_charging_power_k_w = max_charging_power_k_w
        self._charging_efficiency = charging_efficiency
        self._powerfactor = powerfactor
        self._type_application = type_application
        self._hosted_ev = hosted_ev

    @classmethod
    def from_dict(cls, dikt) -> 'ChargingStation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ChargingStation of this ChargingStation.  # noqa: E501
        :rtype: ChargingStation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this ChargingStation.


        :return: The id of this ChargingStation.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this ChargingStation.


        :param id: The id of this ChargingStation.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def bus(self) -> str:
        """Gets the bus of this ChargingStation.

        ID for the connected bus  # noqa: E501

        :return: The bus of this ChargingStation.
        :rtype: str
        """
        return self._bus

    @bus.setter
    def bus(self, bus: str):
        """Sets the bus of this ChargingStation.

        ID for the connected bus  # noqa: E501

        :param bus: The bus of this ChargingStation.
        :type bus: str
        """
        if bus is None:
            raise ValueError("Invalid value for `bus`, must not be `None`")  # noqa: E501

        self._bus = bus

    @property
    def phases(self) -> int:
        """Gets the phases of this ChargingStation.


        :return: The phases of this ChargingStation.
        :rtype: int
        """
        return self._phases

    @phases.setter
    def phases(self, phases: int):
        """Sets the phases of this ChargingStation.


        :param phases: The phases of this ChargingStation.
        :type phases: int
        """

        self._phases = phases

    @property
    def k_v(self) -> float:
        """Gets the k_v of this ChargingStation.


        :return: The k_v of this ChargingStation.
        :rtype: float
        """
        return self._k_v

    @k_v.setter
    def k_v(self, k_v: float):
        """Sets the k_v of this ChargingStation.


        :param k_v: The k_v of this ChargingStation.
        :type k_v: float
        """

        self._k_v = k_v

    @property
    def max_charging_power_k_w(self) -> float:
        """Gets the max_charging_power_k_w of this ChargingStation.


        :return: The max_charging_power_k_w of this ChargingStation.
        :rtype: float
        """
        return self._max_charging_power_k_w

    @max_charging_power_k_w.setter
    def max_charging_power_k_w(self, max_charging_power_k_w: float):
        """Sets the max_charging_power_k_w of this ChargingStation.


        :param max_charging_power_k_w: The max_charging_power_k_w of this ChargingStation.
        :type max_charging_power_k_w: float
        """

        self._max_charging_power_k_w = max_charging_power_k_w

    @property
    def charging_efficiency(self) -> float:
        """Gets the charging_efficiency of this ChargingStation.


        :return: The charging_efficiency of this ChargingStation.
        :rtype: float
        """
        return self._charging_efficiency

    @charging_efficiency.setter
    def charging_efficiency(self, charging_efficiency: float):
        """Sets the charging_efficiency of this ChargingStation.


        :param charging_efficiency: The charging_efficiency of this ChargingStation.
        :type charging_efficiency: float
        """
        if charging_efficiency is not None and charging_efficiency > 100:  # noqa: E501
            raise ValueError("Invalid value for `charging_efficiency`, must be a value less than or equal to `100`")  # noqa: E501
        if charging_efficiency is not None and charging_efficiency < 0:  # noqa: E501
            raise ValueError("Invalid value for `charging_efficiency`, must be a value greater than or equal to `0`")  # noqa: E501

        self._charging_efficiency = charging_efficiency

    @property
    def powerfactor(self) -> float:
        """Gets the powerfactor of this ChargingStation.


        :return: The powerfactor of this ChargingStation.
        :rtype: float
        """
        return self._powerfactor

    @powerfactor.setter
    def powerfactor(self, powerfactor: float):
        """Sets the powerfactor of this ChargingStation.


        :param powerfactor: The powerfactor of this ChargingStation.
        :type powerfactor: float
        """

        self._powerfactor = powerfactor

    @property
    def type_application(self) -> str:
        """Gets the type_application of this ChargingStation.

        residential or commercial  # noqa: E501

        :return: The type_application of this ChargingStation.
        :rtype: str
        """
        return self._type_application

    @type_application.setter
    def type_application(self, type_application: str):
        """Sets the type_application of this ChargingStation.

        residential or commercial  # noqa: E501

        :param type_application: The type_application of this ChargingStation.
        :type type_application: str
        """
        if type_application is None:
            raise ValueError("Invalid value for `type_application`, must not be `None`")  # noqa: E501

        self._type_application = type_application

    @property
    def hosted_ev(self) -> List[ElectricVehicle]:
        """Gets the hosted_ev of this ChargingStation.


        :return: The hosted_ev of this ChargingStation.
        :rtype: List[ElectricVehicle]
        """
        return self._hosted_ev

    @hosted_ev.setter
    def hosted_ev(self, hosted_ev: List[ElectricVehicle]):
        """Sets the hosted_ev of this ChargingStation.


        :param hosted_ev: The hosted_ev of this ChargingStation.
        :type hosted_ev: List[ElectricVehicle]
        """

        self._hosted_ev = hosted_ev
