# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Coordinates(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, latitude: int=None, longitude: int=None):  # noqa: E501
        """Coordinates - a model defined in Swagger

        :param latitude: The latitude of this Coordinates.  # noqa: E501
        :type latitude: int
        :param longitude: The longitude of this Coordinates.  # noqa: E501
        :type longitude: int
        """
        self.swagger_types = {
            'latitude': int,
            'longitude': int
        }

        self.attribute_map = {
            'latitude': 'latitude',
            'longitude': 'longitude'
        }

        self._latitude = latitude
        self._longitude = longitude

    @classmethod
    def from_dict(cls, dikt) -> 'Coordinates':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Coordinates of this Coordinates.  # noqa: E501
        :rtype: Coordinates
        """
        return util.deserialize_model(dikt, cls)

    @property
    def latitude(self) -> int:
        """Gets the latitude of this Coordinates.


        :return: The latitude of this Coordinates.
        :rtype: int
        """
        return self._latitude

    @latitude.setter
    def latitude(self, latitude: int):
        """Sets the latitude of this Coordinates.


        :param latitude: The latitude of this Coordinates.
        :type latitude: int
        """

        self._latitude = latitude

    @property
    def longitude(self) -> int:
        """Gets the longitude of this Coordinates.


        :return: The longitude of this Coordinates.
        :rtype: int
        """
        return self._longitude

    @longitude.setter
    def longitude(self, longitude: int):
        """Sets the longitude of this Coordinates.


        :param longitude: The longitude of this Coordinates.
        :type longitude: int
        """

        self._longitude = longitude
