# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401
from swagger_server.models.phase_val import PhaseVal
from swagger_server.models.base_model_ import Model
from swagger_server import util


class Currents(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, node: PhaseVal=None):  # noqa: E501
        """Currents - a model defined in Swagger

        :param node: The node of this Currents.  # noqa: E501
        :type node: PhaseVal
        """
        self.swagger_types = {
            'node': PhaseVal
        }

        self.attribute_map = {
            'node': 'node'
        }

        self._node = node

    @classmethod
    def from_dict(cls, dikt) -> 'Currents':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Currents of this Currents.  # noqa: E501
        :rtype: Currents
        """
        return util.deserialize_model(dikt, cls)

    @property
    def node(self) -> PhaseVal:
        """Gets the node of this Currents.


        :return: The node of this Currents.
        :rtype: PhaseVal
        """
        return self._node

    @node.setter
    def node(self, node: PhaseVal):
        """Sets the node of this Currents.


        :param node: The node of this Currents.
        :type node: PhaseVal
        """

        self._node = node
