# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Duration(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, day: int=None, month: int=None, year: int=None):  # noqa: E501
        """Duration - a model defined in Swagger

        :param day: The day of this Duration.  # noqa: E501
        :type day: int
        :param month: The month of this Duration.  # noqa: E501
        :type month: int
        :param year: The year of this Duration.  # noqa: E501
        :type year: int
        """
        self.swagger_types = {
            'day': int,
            'month': int,
            'year': int
        }

        self.attribute_map = {
            'day': 'day',
            'month': 'month',
            'year': 'year'
        }

        self._day = day
        self._month = month
        self._year = year

    @classmethod
    def from_dict(cls, dikt) -> 'Duration':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Duration of this Duration.  # noqa: E501
        :rtype: Duration
        """
        return util.deserialize_model(dikt, cls)

    @property
    def day(self) -> int:
        """Gets the day of this Duration.


        :return: The day of this Duration.
        :rtype: int
        """
        return self._day

    @day.setter
    def day(self, day: int):
        """Sets the day of this Duration.


        :param day: The day of this Duration.
        :type day: int
        """

        self._day = day

    @property
    def month(self) -> int:
        """Gets the month of this Duration.


        :return: The month of this Duration.
        :rtype: int
        """
        return self._month

    @month.setter
    def month(self, month: int):
        """Sets the month of this Duration.


        :param month: The month of this Duration.
        :type month: int
        """

        self._month = month

    @property
    def year(self) -> int:
        """Gets the year of this Duration.


        :return: The year of this Duration.
        :rtype: int
        """
        return self._year

    @year.setter
    def year(self, year: int):
        """Sets the year of this Duration.


        :param year: The year of this Duration.
        :type year: int
        """

        self._year = year
