# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Loadshape(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, npts: float=None, interval: float=None, mult: List[float]=None):  # noqa: E501
        """Loadshape - a model defined in Swagger

        :param id: The id of this Loadshape.  # noqa: E501
        :type id: str
        :param npts: The npts of this Loadshape.  # noqa: E501
        :type npts: float
        :param interval: The interval of this Loadshape.  # noqa: E501
        :type interval: float
        :param mult: The mult of this Loadshape.  # noqa: E501
        :type mult: List[float]
        """
        self.swagger_types = {
            'id': str,
            'npts': float,
            'interval': float,
            'mult': List[float]
        }

        self.attribute_map = {
            'id': 'id',
            'npts': 'npts',
            'interval': 'interval',
            'mult': 'mult'
        }

        self._id = id
        self._npts = npts
        self._interval = interval
        self._mult = mult

    @classmethod
    def from_dict(cls, dikt) -> 'Loadshape':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Loadshape of this Loadshape.  # noqa: E501
        :rtype: Loadshape
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Loadshape.


        :return: The id of this Loadshape.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Loadshape.


        :param id: The id of this Loadshape.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def npts(self) -> float:
        """Gets the npts of this Loadshape.


        :return: The npts of this Loadshape.
        :rtype: float
        """
        return self._npts

    @npts.setter
    def npts(self, npts: float):
        """Sets the npts of this Loadshape.


        :param npts: The npts of this Loadshape.
        :type npts: float
        """
        if npts is None:
            raise ValueError("Invalid value for `npts`, must not be `None`")  # noqa: E501

        self._npts = npts

    @property
    def interval(self) -> float:
        """Gets the interval of this Loadshape.


        :return: The interval of this Loadshape.
        :rtype: float
        """
        return self._interval

    @interval.setter
    def interval(self, interval: float):
        """Sets the interval of this Loadshape.


        :param interval: The interval of this Loadshape.
        :type interval: float
        """
        if interval is None:
            raise ValueError("Invalid value for `interval`, must not be `None`")  # noqa: E501

        self._interval = interval

    @property
    def mult(self) -> List[float]:
        """Gets the mult of this Loadshape.


        :return: The mult of this Loadshape.
        :rtype: List[float]
        """
        return self._mult

    @mult.setter
    def mult(self, mult: List[float]):
        """Sets the mult of this Loadshape.


        :param mult: The mult of this Loadshape.
        :type mult: List[float]
        """
        if mult is None:
            raise ValueError("Invalid value for `mult`, must not be `None`")  # noqa: E501

        self._mult = mult
