# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Node(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: int=None, latitude: int=None, longitude: int=None):  # noqa: E501
        """Node - a model defined in Swagger

        :param id: The id of this Node.  # noqa: E501
        :type id: int
        :param latitude: The latitude of this Node.  # noqa: E501
        :type latitude: int
        :param longitude: The longitude of this Node.  # noqa: E501
        :type longitude: int
        """
        self.swagger_types = {
            'id': int,
            'latitude': int,
            'longitude': int
        }

        self.attribute_map = {
            'id': 'id',
            'latitude': 'latitude',
            'longitude': 'longitude'
        }

        self._id = id
        self._latitude = latitude
        self._longitude = longitude

    @classmethod
    def from_dict(cls, dikt) -> 'Node':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Node of this Node.  # noqa: E501
        :rtype: Node
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Node.


        :return: The id of this Node.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Node.


        :param id: The id of this Node.
        :type id: int
        """

        self._id = id

    @property
    def latitude(self) -> int:
        """Gets the latitude of this Node.


        :return: The latitude of this Node.
        :rtype: int
        """
        return self._latitude

    @latitude.setter
    def latitude(self, latitude: int):
        """Sets the latitude of this Node.


        :param latitude: The latitude of this Node.
        :type latitude: int
        """

        self._latitude = latitude

    @property
    def longitude(self) -> int:
        """Gets the longitude of this Node.


        :return: The longitude of this Node.
        :rtype: int
        """
        return self._longitude

    @longitude.setter
    def longitude(self, longitude: int):
        """Sets the longitude of this Node.


        :param longitude: The longitude of this Node.
        :type longitude: int
        """

        self._longitude = longitude
