# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class PhaseValMaxMin(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, maxmin: float=None):  # noqa: E501
        """PhaseValMaxMin - a model defined in Swagger

        :param maxmin: The maxmin of this PhaseValMaxMin.  # noqa: E501
        :type maxmin: float
        """
        self.swagger_types = {
            'maxmin': float
        }

        self.attribute_map = {
            'maxmin': 'max/min'
        }

        self._maxmin = maxmin

    @classmethod
    def from_dict(cls, dikt) -> 'PhaseValMaxMin':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PhaseValMaxMin of this PhaseValMaxMin.  # noqa: E501
        :rtype: PhaseValMaxMin
        """
        return util.deserialize_model(dikt, cls)

    @property
    def maxmin(self) -> float:
        """Gets the maxmin of this PhaseValMaxMin.


        :return: The maxmin of this PhaseValMaxMin.
        :rtype: float
        """
        return self._maxmin

    @maxmin.setter
    def maxmin(self, maxmin: float):
        """Sets the maxmin of this PhaseValMaxMin.


        :param maxmin: The maxmin of this PhaseValMaxMin.
        :type maxmin: float
        """

        self._maxmin = maxmin
