# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class PhaseVal(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, phase: float=None):  # noqa: E501
        """PhaseVal - a model defined in Swagger

        :param phase: The phase of this PhaseVal.  # noqa: E501
        :type phase: float
        """
        self.swagger_types = {
            'phase': float
        }

        self.attribute_map = {
            'phase': 'phase'
        }

        self._phase = phase

    @classmethod
    def from_dict(cls, dikt) -> 'PhaseVal':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PhaseVal of this PhaseVal.  # noqa: E501
        :rtype: PhaseVal
        """
        return util.deserialize_model(dikt, cls)

    @property
    def phase(self) -> float:
        """Gets the phase of this PhaseVal.


        :return: The phase of this PhaseVal.
        :rtype: float
        """
        return self._phase

    @phase.setter
    def phase(self, phase: float):
        """Sets the phase of this PhaseVal.


        :param phase: The phase of this PhaseVal.
        :type phase: float
        """

        self._phase = phase
