# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401
from swagger_server.models.phase_val_max_min import PhaseValMaxMin
from swagger_server.models.base_model_ import Model
from swagger_server import util


class PhaseValue(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, phase: PhaseValMaxMin=None):  # noqa: E501
        """PhaseValue - a model defined in Swagger

        :param phase: The phase of this PhaseValue.  # noqa: E501
        :type phase: PhaseValMaxMin
        """
        self.swagger_types = {
            'phase': PhaseValMaxMin
        }

        self.attribute_map = {
            'phase': 'phase'
        }

        self._phase = phase

    @classmethod
    def from_dict(cls, dikt) -> 'PhaseValue':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PhaseValue of this PhaseValue.  # noqa: E501
        :rtype: PhaseValue
        """
        return util.deserialize_model(dikt, cls)

    @property
    def phase(self) -> PhaseValMaxMin:
        """Gets the phase of this PhaseValue.


        :return: The phase of this PhaseValue.
        :rtype: PhaseValMaxMin
        """
        return self._phase

    @phase.setter
    def phase(self, phase: PhaseValMaxMin):
        """Sets the phase of this PhaseValue.


        :param phase: The phase of this PhaseValue.
        :type phase: PhaseValMaxMin
        """

        self._phase = phase
