# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Powers(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, node: float=None):  # noqa: E501
        """Powers - a model defined in Swagger

        :param node: The node of this Powers.  # noqa: E501
        :type node: float
        """
        self.swagger_types = {
            'node': float
        }

        self.attribute_map = {
            'node': 'node'
        }

        self._node = node

    @classmethod
    def from_dict(cls, dikt) -> 'Powers':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Powers of this Powers.  # noqa: E501
        :rtype: Powers
        """
        return util.deserialize_model(dikt, cls)

    @property
    def node(self) -> float:
        """Gets the node of this Powers.


        :return: The node of this Powers.
        :rtype: float
        """
        return self._node

    @node.setter
    def node(self, node: float):
        """Sets the node of this Powers.


        :param node: The node of this Powers.
        :type node: float
        """

        self._node = node
