# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.transformer_regcontrol import TransformerRegcontrol  # noqa: F401,E501
from swagger_server.models.transformer_wdgs import TransformerWdgs  # noqa: F401,E501
from swagger_server import util


class Transformer(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, phases: int=None, windings: int=None, kvas: List[float]=None, buses: List[str]=None, kvs: List[float]=None, wdgs: TransformerWdgs=None, regcontrol: TransformerRegcontrol=None, xhl: float=None, xlt: float=None, xht: float=None, percent_load_loss: float=None, bank: str=None, tap_level: float=None, base_frequency: float=None):  # noqa: E501
        """Transformer - a model defined in Swagger

        :param id: The id of this Transformer.  # noqa: E501
        :type id: str
        :param phases: The phases of this Transformer.  # noqa: E501
        :type phases: int
        :param windings: The windings of this Transformer.  # noqa: E501
        :type windings: int
        :param kvas: The kvas of this Transformer.  # noqa: E501
        :type kvas: List[float]
        :param buses: The buses of this Transformer.  # noqa: E501
        :type buses: List[str]
        :param kvs: The kvs of this Transformer.  # noqa: E501
        :type kvs: List[float]
        :param wdgs: The wdgs of this Transformer.  # noqa: E501
        :type wdgs: TransformerWdgs
        :param regcontrol: The regcontrol of this Transformer.  # noqa: E501
        :type regcontrol: TransformerRegcontrol
        :param xhl: The xhl of this Transformer.  # noqa: E501
        :type xhl: float
        :param xlt: The xlt of this Transformer.  # noqa: E501
        :type xlt: float
        :param xht: The xht of this Transformer.  # noqa: E501
        :type xht: float
        :param percent_load_loss: The percent_load_loss of this Transformer.  # noqa: E501
        :type percent_load_loss: float
        :param bank: The bank of this Transformer.  # noqa: E501
        :type bank: str
        :param tap_level: The tap_level of this Transformer.  # noqa: E501
        :type tap_level: float
        :param base_frequency: The base_frequency of this Transformer.  # noqa: E501
        :type base_frequency: float
        """
        self.swagger_types = {
            'id': str,
            'phases': int,
            'windings': int,
            'kvas': List[float],
            'buses': List[str],
            'kvs': List[float],
            'wdgs': TransformerWdgs,
            'regcontrol': TransformerRegcontrol,
            'xhl': float,
            'xlt': float,
            'xht': float,
            'percent_load_loss': float,
            'bank': str,
            'tap_level': float,
            'base_frequency': float
        }

        self.attribute_map = {
            'id': 'id',
            'phases': 'phases',
            'windings': 'windings',
            'kvas': 'kvas',
            'buses': 'buses',
            'kvs': 'kvs',
            'wdgs': 'wdgs',
            'regcontrol': 'regcontrol',
            'xhl': 'xhl',
            'xlt': 'xlt',
            'xht': 'xht',
            'percent_load_loss': 'percent_load_loss',
            'bank': 'bank',
            'tap_level': 'tapLevel',
            'base_frequency': 'base_frequency'
        }

        self._id = id
        self._phases = phases
        self._windings = windings
        self._kvas = kvas
        self._buses = buses
        self._kvs = kvs
        self._wdgs = wdgs
        self._regcontrol = regcontrol
        self._xhl = xhl
        self._xlt = xlt
        self._xht = xht
        self._percent_load_loss = percent_load_loss
        self._bank = bank
        self._tap_level = tap_level
        self._base_frequency = base_frequency

    @classmethod
    def from_dict(cls, dikt) -> 'Transformer':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Transformer of this Transformer.  # noqa: E501
        :rtype: Transformer
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Transformer.


        :return: The id of this Transformer.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Transformer.


        :param id: The id of this Transformer.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def phases(self) -> int:
        """Gets the phases of this Transformer.

        Number of Phases  # noqa: E501

        :return: The phases of this Transformer.
        :rtype: int
        """
        return self._phases

    @phases.setter
    def phases(self, phases: int):
        """Sets the phases of this Transformer.

        Number of Phases  # noqa: E501

        :param phases: The phases of this Transformer.
        :type phases: int
        """
        if phases is None:
            raise ValueError("Invalid value for `phases`, must not be `None`")  # noqa: E501

        self._phases = phases

    @property
    def windings(self) -> int:
        """Gets the windings of this Transformer.

        number of windings  # noqa: E501

        :return: The windings of this Transformer.
        :rtype: int
        """
        return self._windings

    @windings.setter
    def windings(self, windings: int):
        """Sets the windings of this Transformer.

        number of windings  # noqa: E501

        :param windings: The windings of this Transformer.
        :type windings: int
        """
        if windings is None:
            raise ValueError("Invalid value for `windings`, must not be `None`")  # noqa: E501

        self._windings = windings

    @property
    def kvas(self) -> List[float]:
        """Gets the kvas of this Transformer.


        :return: The kvas of this Transformer.
        :rtype: List[float]
        """
        return self._kvas

    @kvas.setter
    def kvas(self, kvas: List[float]):
        """Sets the kvas of this Transformer.


        :param kvas: The kvas of this Transformer.
        :type kvas: List[float]
        """

        self._kvas = kvas

    @property
    def buses(self) -> List[str]:
        """Gets the buses of this Transformer.


        :return: The buses of this Transformer.
        :rtype: List[str]
        """
        return self._buses

    @buses.setter
    def buses(self, buses: List[str]):
        """Sets the buses of this Transformer.


        :param buses: The buses of this Transformer.
        :type buses: List[str]
        """

        self._buses = buses

    @property
    def kvs(self) -> List[float]:
        """Gets the kvs of this Transformer.


        :return: The kvs of this Transformer.
        :rtype: List[float]
        """
        return self._kvs

    @kvs.setter
    def kvs(self, kvs: List[float]):
        """Sets the kvs of this Transformer.


        :param kvs: The kvs of this Transformer.
        :type kvs: List[float]
        """

        self._kvs = kvs

    @property
    def wdgs(self) -> TransformerWdgs:
        """Gets the wdgs of this Transformer.


        :return: The wdgs of this Transformer.
        :rtype: TransformerWdgs
        """
        return self._wdgs

    @wdgs.setter
    def wdgs(self, wdgs: TransformerWdgs):
        """Sets the wdgs of this Transformer.


        :param wdgs: The wdgs of this Transformer.
        :type wdgs: TransformerWdgs
        """

        self._wdgs = wdgs

    @property
    def regcontrol(self) -> TransformerRegcontrol:
        """Gets the regcontrol of this Transformer.


        :return: The regcontrol of this Transformer.
        :rtype: TransformerRegcontrol
        """
        return self._regcontrol

    @regcontrol.setter
    def regcontrol(self, regcontrol: TransformerRegcontrol):
        """Sets the regcontrol of this Transformer.


        :param regcontrol: The regcontrol of this Transformer.
        :type regcontrol: TransformerRegcontrol
        """

        self._regcontrol = regcontrol

    @property
    def xhl(self) -> float:
        """Gets the xhl of this Transformer.

        Percent reactance high-to-low (winding 1 to winding 2)  # noqa: E501

        :return: The xhl of this Transformer.
        :rtype: float
        """
        return self._xhl

    @xhl.setter
    def xhl(self, xhl: float):
        """Sets the xhl of this Transformer.

        Percent reactance high-to-low (winding 1 to winding 2)  # noqa: E501

        :param xhl: The xhl of this Transformer.
        :type xhl: float
        """
        if xhl is None:
            raise ValueError("Invalid value for `xhl`, must not be `None`")  # noqa: E501

        self._xhl = xhl

    @property
    def xlt(self) -> float:
        """Gets the xlt of this Transformer.

        Percent reactance high-to-low (winding 2 to winding 3)  # noqa: E501

        :return: The xlt of this Transformer.
        :rtype: float
        """
        return self._xlt

    @xlt.setter
    def xlt(self, xlt: float):
        """Sets the xlt of this Transformer.

        Percent reactance high-to-low (winding 2 to winding 3)  # noqa: E501

        :param xlt: The xlt of this Transformer.
        :type xlt: float
        """

        self._xlt = xlt

    @property
    def xht(self) -> float:
        """Gets the xht of this Transformer.

        Percent reactance high-to-low (winding 1 to winding 3)  # noqa: E501

        :return: The xht of this Transformer.
        :rtype: float
        """
        return self._xht

    @xht.setter
    def xht(self, xht: float):
        """Sets the xht of this Transformer.

        Percent reactance high-to-low (winding 1 to winding 3)  # noqa: E501

        :param xht: The xht of this Transformer.
        :type xht: float
        """

        self._xht = xht

    @property
    def percent_load_loss(self) -> float:
        """Gets the percent_load_loss of this Transformer.

        Percent reactance high-to-low (winding 1 to winding 3)  # noqa: E501

        :return: The percent_load_loss of this Transformer.
        :rtype: float
        """
        return self._percent_load_loss

    @percent_load_loss.setter
    def percent_load_loss(self, percent_load_loss: float):
        """Sets the percent_load_loss of this Transformer.

        Percent reactance high-to-low (winding 1 to winding 3)  # noqa: E501

        :param percent_load_loss: The percent_load_loss of this Transformer.
        :type percent_load_loss: float
        """
        if percent_load_loss is not None and percent_load_loss > 1:  # noqa: E501
            raise ValueError("Invalid value for `percent_load_loss`, must be a value less than or equal to `1`")  # noqa: E501
        if percent_load_loss is not None and percent_load_loss < 0:  # noqa: E501
            raise ValueError("Invalid value for `percent_load_loss`, must be a value greater than or equal to `0`")  # noqa: E501

        self._percent_load_loss = percent_load_loss

    @property
    def bank(self) -> str:
        """Gets the bank of this Transformer.

        Name of the bank this transformer is part of  # noqa: E501

        :return: The bank of this Transformer.
        :rtype: str
        """
        return self._bank

    @bank.setter
    def bank(self, bank: str):
        """Sets the bank of this Transformer.

        Name of the bank this transformer is part of  # noqa: E501

        :param bank: The bank of this Transformer.
        :type bank: str
        """

        self._bank = bank

    @property
    def tap_level(self) -> float:
        """Gets the tap_level of this Transformer.


        :return: The tap_level of this Transformer.
        :rtype: float
        """
        return self._tap_level

    @tap_level.setter
    def tap_level(self, tap_level: float):
        """Sets the tap_level of this Transformer.


        :param tap_level: The tap_level of this Transformer.
        :type tap_level: float
        """

        self._tap_level = tap_level

    @property
    def base_frequency(self) -> float:
        """Gets the base_frequency of this Transformer.


        :return: The base_frequency of this Transformer.
        :rtype: float
        """
        return self._base_frequency

    @base_frequency.setter
    def base_frequency(self, base_frequency: float):
        """Sets the base_frequency of this Transformer.


        :param base_frequency: The base_frequency of this Transformer.
        :type base_frequency: float
        """

        self._base_frequency = base_frequency
