# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.winding import Winding  # noqa: F401,E501
from swagger_server import util


class TransformerWdgs(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, struct: List[Winding]=None):  # noqa: E501
        """TransformerWdgs - a model defined in Swagger

        :param struct: The struct of this TransformerWdgs.  # noqa: E501
        :type struct: List[Winding]
        """
        self.swagger_types = {
            'struct': List[Winding]
        }

        self.attribute_map = {
            'struct': 'struct'
        }

        self._struct = struct

    @classmethod
    def from_dict(cls, dikt) -> 'TransformerWdgs':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Transformer_wdgs of this TransformerWdgs.  # noqa: E501
        :rtype: TransformerWdgs
        """
        return util.deserialize_model(dikt, cls)

    @property
    def struct(self) -> List[Winding]:
        """Gets the struct of this TransformerWdgs.


        :return: The struct of this TransformerWdgs.
        :rtype: List[Winding]
        """
        return self._struct

    @struct.setter
    def struct(self, struct: List[Winding]):
        """Sets the struct of this TransformerWdgs.


        :param struct: The struct of this TransformerWdgs.
        :type struct: List[Winding]
        """

        self._struct = struct
