# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.reg_control import RegControl  # noqa: F401,E501
from swagger_server import util


class TransformerRegcontrol(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, struct: List[RegControl]=None):  # noqa: E501
        """TransformerRegcontrol - a model defined in Swagger

        :param struct: The struct of this TransformerRegcontrol.  # noqa: E501
        :type struct: List[RegControl]
        """
        self.swagger_types = {
            'struct': List[RegControl]
        }

        self.attribute_map = {
            'struct': 'struct'
        }

        self._struct = struct

    @classmethod
    def from_dict(cls, dikt) -> 'TransformerRegcontrol':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Transformer_regcontrol of this TransformerRegcontrol.  # noqa: E501
        :rtype: TransformerRegcontrol
        """
        return util.deserialize_model(dikt, cls)

    @property
    def struct(self) -> List[RegControl]:
        """Gets the struct of this TransformerRegcontrol.


        :return: The struct of this TransformerRegcontrol.
        :rtype: List[RegControl]
        """
        return self._struct

    @struct.setter
    def struct(self, struct: List[RegControl]):
        """Sets the struct of this TransformerRegcontrol.


        :param struct: The struct of this TransformerRegcontrol.
        :type struct: List[RegControl]
        """

        self._struct = struct
