# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Tshape(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, npts: float=None, interval: float=None, temp: List[float]=None):  # noqa: E501
        """Tshape - a model defined in Swagger

        :param id: The id of this Tshape.  # noqa: E501
        :type id: str
        :param npts: The npts of this Tshape.  # noqa: E501
        :type npts: float
        :param interval: The interval of this Tshape.  # noqa: E501
        :type interval: float
        :param temp: The temp of this Tshape.  # noqa: E501
        :type temp: List[float]
        """
        self.swagger_types = {
            'id': str,
            'npts': float,
            'interval': float,
            'temp': List[float]
        }

        self.attribute_map = {
            'id': 'id',
            'npts': 'npts',
            'interval': 'interval',
            'temp': 'temp'
        }

        self._id = id
        self._npts = npts
        self._interval = interval
        self._temp = temp

    @classmethod
    def from_dict(cls, dikt) -> 'Tshape':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Tshape of this Tshape.  # noqa: E501
        :rtype: Tshape
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Tshape.


        :return: The id of this Tshape.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Tshape.


        :param id: The id of this Tshape.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def npts(self) -> float:
        """Gets the npts of this Tshape.


        :return: The npts of this Tshape.
        :rtype: float
        """
        return self._npts

    @npts.setter
    def npts(self, npts: float):
        """Sets the npts of this Tshape.


        :param npts: The npts of this Tshape.
        :type npts: float
        """
        if npts is None:
            raise ValueError("Invalid value for `npts`, must not be `None`")  # noqa: E501

        self._npts = npts

    @property
    def interval(self) -> float:
        """Gets the interval of this Tshape.


        :return: The interval of this Tshape.
        :rtype: float
        """
        return self._interval

    @interval.setter
    def interval(self, interval: float):
        """Sets the interval of this Tshape.


        :param interval: The interval of this Tshape.
        :type interval: float
        """
        if interval is None:
            raise ValueError("Invalid value for `interval`, must not be `None`")  # noqa: E501

        self._interval = interval

    @property
    def temp(self) -> List[float]:
        """Gets the temp of this Tshape.


        :return: The temp of this Tshape.
        :rtype: List[float]
        """
        return self._temp

    @temp.setter
    def temp(self, temp: List[float]):
        """Sets the temp of this Tshape.


        :param temp: The temp of this Tshape.
        :type temp: List[float]
        """
        if temp is None:
            raise ValueError("Invalid value for `temp`, must not be `None`")  # noqa: E501

        self._temp = temp
