# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401
from swagger_server.models.phase_value import PhaseValue
from swagger_server.models.base_model_ import Model
from swagger_server import util


class Voltages(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, node: PhaseValue=None):  # noqa: E501
        """Voltages - a model defined in Swagger

        :param node: The node of this Voltages.  # noqa: E501
        :type node: PhaseValue
        """
        self.swagger_types = {
            'node': PhaseValue
        }

        self.attribute_map = {
            'node': 'node'
        }

        self._node = node

    @classmethod
    def from_dict(cls, dikt) -> 'Voltages':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Voltages of this Voltages.  # noqa: E501
        :rtype: Voltages
        """
        return util.deserialize_model(dikt, cls)

    @property
    def node(self) -> PhaseValue:
        """Gets the node of this Voltages.


        :return: The node of this Voltages.
        :rtype: PhaseValue
        """
        return self._node

    @node.setter
    def node(self, node: PhaseValue):
        """Sets the node of this Voltages.


        :param node: The node of this Voltages.
        :type node: PhaseValue
        """

        self._node = node
